spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atmg?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 86138160Xxy
  jpa:
    show-sql: true

server:
  port: 80

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml # MyBatis XML映射文件的路径
  global-config:
    capitalMode: true
    banner: false
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_null
  type-aliases-package: com.gc.draw.entity # 实体类的包路径
  configuration:
      jdbc-type-for-null: 'null'
      call-setters-on-nulls: true
      shrink-whitespaces-in-sql: true
mybatis-plus-join:
  banner: false #关闭连表查询组件banner

logging:
  level:
    com.baomidou.mybatisplus.core.log: debug

file:
  video-directory: D:\project\atmg\file\videos
  image-directory: D:\project\atmg\file\images